version: '3.8'

services:
  web:
    image: secros18/app-dental-web
    ports:
      - "8080:80"
      - "444:443"
    networks:
      back_mi_red:
        ipv4_address: 172.19.0.5
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    restart: always

networks:
  back_mi_red:
    external: true
