version: '3.8'
services:
   web:
     build:
        context: .
        dockerfile: Dockerfile
     ports:
       - "4200:4200"
     networks:
       back_mi_red:
         ipv4_address: 172.19.0.5
     volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
     environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
     deploy:
      resources:
        limits:
          memory: 2GB
networks:
  back_mi_red:
    external: true


